apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo
  name: postgres-data-pvc
spec:
#  storageClassName: use the default dynamic provisioning class      manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
